# Generated by Django 3.0.6 on 2020-05-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200523_1303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
